# .github/workflows/test-setup-liquibase.yml
name: Test Setup Liquibase PRO

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  LIQUIBASE_LOG_FILE: /liquibase/changelog/liquibase.dev.log.json
  ###
  ### Liquibase specific
  ###
  LB_BASE_DIR: /liquibase/changelog
  LB_ENVIRONMENT: DEV
  LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.main.xml
  LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_OUTPUT: issues
  LIQUIBASE_DBCLHISTORY_ENABLED: true
  
  LIQUIBASE_LOG_FORMAT: json_pretty
  LIQUIBASE_LOG_LEVEL: warning
  LIQUIBASE_MIRROR_CONSOLE_MESSAGES_TO_LOG: false
  LIQUIBASE_SEARCH_PATH: /liquibase/changelog
  LIQUIBASE_SHOW_BANNER: false
  LIQUIBASE_LICENSE_KEY: ${{ secrets.PRO_LICENSE_KEY }}

jobs:
  # 1. Basic Installation Tests
  test-pro-basic:
    name: PRO Basic Installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Liquibase
        uses: liquibase/setup-liquibase@v2.1.0 # Proposed new action
        with:
          edition: "secure" # Parameter to specify 'oss' or 'pro'
          version: "5.0.3" # Or '5.0.0', etc.
          # Potentially other options like license-key for pro

      - name: Verify Installation
        run: |
          liquibase --version
          which liquibase
